// <auto-generated />
namespace RestRestaurante.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddProperty_vrPreco_TablePrato : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProperty_vrPreco_TablePrato));
        
        string IMigrationMetadata.Id
        {
            get { return "201712110325091_AddProperty_vrPreco_TablePrato"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
